name: "onPlay"
description: "music player"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 2.0.0+1

environment:
  sdk:  ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.5

  permission_handler: ^11.3.1


  open_file: ^3.2.1

  # cupertino_icons: ^1.0.6
  metadata_god: ^0.5.2+1
  flutter_local_notifications: ^17.2.2
  audioplayers: ^6.1.0
  palette_generator: ^0.3.3+4
  provider: ^6.1.2
  # wallpaper_handler: ^0.0.2
  flutter_cache_manager: ^3.3.1
  # flutter_wallpaper_manager: ^0.0.4
  audio_service: ^0.18.15
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  collection: ^1.18.0
  go_router: ^14.2.7
  json_annotation: ^4.9.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  volume_controller: ^2.0.8
  package_info_plus: ^8.0.2
  external_path: ^2.0.1
  marquee: ^2.2.3
  http: ^1.2.2
  dio: ^5.7.0
  audiotags: ^1.4.1
  just_audio: ^0.9.42
  # audiotagger: ^2.2.1


objectbox:
  output_dir: database

# json_serializable:combining_builder:
#             generate_for:
#                   - lib/**/dtos/**.dart
# objectbox_generator:combining_builder:
#             generate_for:
#                   - lib/**/models/**.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  #objectbox_generator: any



flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700