import 'package:json_annotation/json_annotation.dart';
import 'package:onPlay/dtos/json/thumbnail_dto.dart';
import 'package:onPlay/services/http/serializable.dart';

part "search_dto.g.dart";

@JsonSerializable()
class SearchDto extends Serializable {
  String type;
  String? title;
  String? videoId;
  String? author;
  String? authorId;
  String? authorUrl;
  List<ThumbnailDto>? videoThumbnails;
  String? playlistId;
  String? playlistThumbnail;
  bool? authorVerified;
  int? videoCount;
  List<VideoItemDto>? videos;
  List<ThumbnailDto>? authorThumbnails;
  bool? autoGenerated;
  int? subCount;
  String? description;
  String? descriptionHtml;
  int? viewCount;
  int? published;
  String? publishedText;
  int? lengthSeconds;
  bool? liveNow;
  bool? paid;
  bool? premium;

  factory SearchDto.fromJson(Map<String, dynamic> json) =>
      _$SearchDtoFromJson(json);
  @override
  Map<String, dynamic> toJson() => _$SearchDtoToJson(this);

  SearchDto({
    required this.type,
    this.title,
    this.videoId,
    this.author,
    this.authorId,
    this.authorUrl,
    this.videoThumbnails,
    this.playlistId,
    this.playlistThumbnail,
    this.authorVerified,
    this.videoCount,
    this.videos,
    this.authorThumbnails,
    this.autoGenerated,
    this.subCount,
    this.description,
    this.descriptionHtml,
    this.viewCount,
    this.published,
    this.publishedText,
    this.lengthSeconds,
    this.liveNow,
    this.paid,
    this.premium,
  });
}

@JsonSerializable()
class VideoItemDto extends Serializable {
  String? title;
  String? videoId;
  int? lengthSeconds;
  List<ThumbnailDto>? videoThumbnails;
  VideoItemDto(
      {this.title, this.videoId, this.lengthSeconds, this.videoThumbnails});

  factory VideoItemDto.fromJson(Map<String, dynamic> json) =>
      _$VideoItemDtoFromJson(json);
  @override
  Map<String, dynamic> toJson() => _$VideoItemDtoToJson(this);
}
