// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'search_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SearchDto _$SearchDtoFromJson(Map<String, dynamic> json) => SearchDto(
      type: json['type'] as String,
      title: json['title'] as String?,
      videoId: json['videoId'] as String?,
      author: json['author'] as String?,
      authorId: json['authorId'] as String?,
      authorUrl: json['authorUrl'] as String?,
      videoThumbnails: (json['videoThumbnails'] as List<dynamic>?)
          ?.map((e) => ThumbnailDto.fromJson(e as Map<String, dynamic>))
          .toList(),
      playlistId: json['playlistId'] as String?,
      playlistThumbnail: json['playlistThumbnail'] as String?,
      authorVerified: json['authorVerified'] as bool?,
      videoCount: (json['videoCount'] as num?)?.toInt(),
      videos: (json['videos'] as List<dynamic>?)
          ?.map((e) => VideoItemDto.fromJson(e as Map<String, dynamic>))
          .toList(),
      authorThumbnails: (json['authorThumbnails'] as List<dynamic>?)
          ?.map((e) => ThumbnailDto.fromJson(e as Map<String, dynamic>))
          .toList(),
      autoGenerated: json['autoGenerated'] as bool?,
      subCount: (json['subCount'] as num?)?.toInt(),
      description: json['description'] as String?,
      descriptionHtml: json['descriptionHtml'] as String?,
      viewCount: (json['viewCount'] as num?)?.toInt(),
      published: (json['published'] as num?)?.toInt(),
      publishedText: json['publishedText'] as String?,
      lengthSeconds: (json['lengthSeconds'] as num?)?.toInt(),
      liveNow: json['liveNow'] as bool?,
      paid: json['paid'] as bool?,
      premium: json['premium'] as bool?,
    );

Map<String, dynamic> _$SearchDtoToJson(SearchDto instance) => <String, dynamic>{
      'type': instance.type,
      'title': instance.title,
      'videoId': instance.videoId,
      'author': instance.author,
      'authorId': instance.authorId,
      'authorUrl': instance.authorUrl,
      'videoThumbnails': instance.videoThumbnails,
      'playlistId': instance.playlistId,
      'playlistThumbnail': instance.playlistThumbnail,
      'authorVerified': instance.authorVerified,
      'videoCount': instance.videoCount,
      'videos': instance.videos,
      'authorThumbnails': instance.authorThumbnails,
      'autoGenerated': instance.autoGenerated,
      'subCount': instance.subCount,
      'description': instance.description,
      'descriptionHtml': instance.descriptionHtml,
      'viewCount': instance.viewCount,
      'published': instance.published,
      'publishedText': instance.publishedText,
      'lengthSeconds': instance.lengthSeconds,
      'liveNow': instance.liveNow,
      'paid': instance.paid,
      'premium': instance.premium,
    };

VideoItemDto _$VideoItemDtoFromJson(Map<String, dynamic> json) => VideoItemDto(
      title: json['title'] as String?,
      videoId: json['videoId'] as String?,
      lengthSeconds: (json['lengthSeconds'] as num?)?.toInt(),
      videoThumbnails: (json['videoThumbnails'] as List<dynamic>?)
          ?.map((e) => ThumbnailDto.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$VideoItemDtoToJson(VideoItemDto instance) =>
    <String, dynamic>{
      'title': instance.title,
      'videoId': instance.videoId,
      'lengthSeconds': instance.lengthSeconds,
      'videoThumbnails': instance.videoThumbnails,
    };
